version: "3.8"

services:
  web_api_gateway:
    container_name: api_gateway_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - ALGORITHM=$ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES

