version: "3.8"

services:
  web_auth:
    container_name: mails_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:8080"
    environment:
      - SMTP_USER=$SMTP_USER
      - SMTP_PASSWORD=$SMTP_PASSWORD

