version: "3.8"

services:
  web_auth:
    container_name: auth_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:8080"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - ALGORITHM=$ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES




