version: "3.8"

services:
  db:
    container_name: users_db
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "usersmicroservice"

  db_test:
    container_name: users_db_test
    image: postgres
    restart: always
    expose:
      - 5433
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "usersmicroservice_test"

  adminer:
    container_name: users_adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  web_users:
    container_name: users_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:8080"
    environment:
      - RABBIT_MQ_ADDRESS=$RABBIT_MQ_ADDRESS
      - SECRET_KEY=$SECRET_KEY
      - ALGORITHM=$ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
    depends_on:
      - db
      - db_test