version: "3.8"

services:
  db:
    container_name: users_db
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "usersmicroservice"

  adminer:
    container_name: users_adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  web_users:
    container_name: users_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:8080"
    environment:
      - RABBIT_MQ_ADDRESS=$RABBIT_MQ_ADDRESS
    depends_on:
      - db