version: "3.8"

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "usersmicroservice"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  web_users:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - db