"""add_email_confirmed_date_time_column_to_users_table

Revision ID: e41e60c5d79a
Revises: 80258caa0d7b
Create Date: 2023-06-26 16:18:59.697798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41e60c5d79a'
down_revision = '80258caa0d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed_date_time', sa.DateTime(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'email_confirmed_date_time')
    # ### end Alembic commands ###
