name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker_compose:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build_user
        run: docker-compose up -f users_service/docker-compose.yml -d --build
      - name: Build_auth
        run: docker-compose up -f auth_service/docker-compose.yml -d --build


